### ISSUE TITLE
Dock doesn't extend right

### ISSUE THREAD

**Issue by reversed95** [Muirey03/Zenith#1]
First of all thanks for making this awesome tweak! The issue can be seen here.
![img_6393](https://user-images.githubusercontent.com/33935450/49328493-38a1ba00-f572-11e8-9e27-defe96c7690b.PNG)
I thought it had to do with fiveicondock but even after uninstalling it still appears like this.

**Comment by lqpnote** [comment]
Yup that’s the only bug I noticed

**Comment by Muirey03** [comment]
Looks like a conflict with another tweak. Do you have FloatingDock installed? Does this still happen when all other tweaks are disabled?

**Comment by fezzzz** [comment]
Same here

**Comment by lqpnote** [comment]
@Muirey03 OP has floating dock installed but I don’t

**Comment by MertCYLN** [comment]
Same, even if you add an app on there; you can not open it. It just changes the pages.


![img_7476](https://user-images.githubusercontent.com/45524532/49334326-28c2be00-f5e4-11e8-9489-e353f928f23a.jpeg)

**Comment by Muirey03** [comment]
For people experiencing this issue, does it occur when all other tweaks are disabled in icleaner, so the only tweaks you have enabled are Zenith and its dependancies? @MertCYLN @lqpnote @fezzzz @reversed95

**Comment by Muirey03** [comment]
I believe this is fixed in v.1.0.1
