### ISSUE TITLE
Swipe down does not work in the dock

### ISSUE THREAD

**Issue by fido7up** [Muirey03/Zenith#11]
Swipe down does not work in the doc.

I don't know if it an issue or a feature. I'd like to have it for sure, I keep doing it and opening the app ^^.

Note : I don't have any dock tweak.

**Comment by Muirey03** [comment]
This is because your finger is going below the screen so iOS registers this a tap not a swipe. Nothing I can do, just swipe up instead.

**Comment by fido7up** [comment]
Ok, I thought I remembered it working with Apex.

**Comment by jffortier249** [comment]
I will confirm that it was working flawless on Apex and not so good on Zenith.
