### ISSUE TITLE
Grabber boxes still visible for icons appearing around active icon 

### ISSUE THREAD

**Issue by ptooey** [Muirey03/Zenith#12]
When Zenith is active on an icon, the grabber boxes on other icons beside the active one are too prominent.

Unsure if possible, but styling-wise, it'd be better if the opacity of these boxes can be tweaked to be less noticeable for the de-focused icons.

![capture](https://user-images.githubusercontent.com/1219080/49332666-7ef42900-f605-11e8-9f7c-027f88847ff2.PNG)

**Comment by Muirey03** [comment]
Not an issue so I'm closing it
