### ISSUE TITLE
Apps Dissappear from Zenith List

### ISSUE THREAD

**Issue by Jenzilly** [Muirey03/Zenith#13]
I nave a couple of apps^ that I cannot select from the Zenith app list. I'm pretty sure this happened when I first used the app^ as the ‘Main’ app to place apps within them, and then I took all sub-apps out and tried to place the ‘Main’ app within another app (I am not trying to make a nested app but i’m pretty sure this is what the tweak thinks i’m trying to do). I can use the apps^ as the main app and place other apps within them again, but I cannot choose the app^ while trying to place them within an app. 
(^ signifies the app that does not appear in Zenith list)

**Comment by Muirey03** [comment]
Thank you for reporting this

**Comment by Muirey03** [comment]
Fixed in v.1.0.1
