### ISSUE TITLE
Expends after the Notification Center closes and breaks Notification Center

### ISSUE THREAD

**Issue by fido7up** [Muirey03/Zenith#15]
If, when I drop down the Notification Center, my finger is to close to a top row icon, the icon will start to expend while the Notification Center fully closes.

And sometimes when I drop down the Notification Center, with similar finger placement, my keyboards appears with the Notification Center and when I close it the research windows is already open (explaining the keybord) but the icon doesn't expend in that case. It never happens without the tweak.

I have an iPhone SE.

**Comment by Muirey03** [comment]
The second issue can be explained by the search gesture option you are using (I assume you are using swipe down). The first doesn't really sound like an issue and is simply caused by you swiping down on an icon accidentally.
