### ISSUE TITLE
Some previews are on the wrong side

### ISSUE THREAD

**Issue by MertCYLN** [Muirey03/Zenith#19]
Thanks for that great tweak!!! I was willing it to come soon for a long time (:..

The issue is like in the title and on the photos.

![img_7474](https://user-images.githubusercontent.com/45524532/49334308-a803c200-f5e3-11e8-8933-8e5392a78410.jpeg)
![img_7475](https://user-images.githubusercontent.com/45524532/49334310-b356ed80-f5e3-11e8-89a5-5218164799ff.jpeg)

**Comment by Muirey03** [comment]
This is not really an issue. It is because you have placed the icon in the top slot of an icon, but when you expand it, it cannot expand upwards as it is on the top row, so it expands downwards instead. If you want the grabber to appear on the bottom, put the app in the bottom slot.

**Comment by MertCYLN** [comment]
Noooo, I made it like how u said it should be. Removing them and adding them from the right side doesn’t fix that...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Muirey03** [comment]
It's not difficult. If you want the grabber to appear on the bottom, expand the icon, edit it and select the VERY BOTTOM slot for your icon

**Comment by MertCYLN** [comment]
I can understand that. Ofc i am aware of it. But when I want to add 2 apps behind the Phone.app’s right it shows on both sides.

I got it. It is not a real bug or issue. But i guess it is not how it should work.

I love your works. I love that tweak. Thank you so much. But, this is why you want feedbacks right? Sorry if i am bothering.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
