### ISSUE TITLE
Small tabs don't match actual hidden apps

### ISSUE THREAD

**Issue by reversed95** [Muirey03/Zenith#2]
![img_6394](https://user-images.githubusercontent.com/33935450/49328525-b9f94c80-f572-11e8-896a-9d30dcb6263a.PNG)
![img_6395](https://user-images.githubusercontent.com/33935450/49328526-b9f94c80-f572-11e8-9920-4b49ad78634e.PNG)

**Comment by Muirey03** [comment]
The indicators show that there is an app below that icon. Because the app is on the bottom row, any apps on the bottom must be expanded upwards otherwise they will go off the screen. If you want the indicator to appear at the top of the icon, add the sub-app in the icon's top slot
