### ISSUE TITLE
Apps open with touch and no 3D touch menu

### ISSUE THREAD

**Issue by MertCYLN** [Muirey03/Zenith#20]
If there is an app on the back, it opens by touching it. Not when I release my finger.
And it doesn’t let me see 3D menus of the apps behind.

**Comment by Muirey03** [comment]
This is unfortunately unfixable due to the way UIKit handles hit rendering outside of a parent view's bounds. Sorry.

**Comment by MertCYLN** [comment]
Ouu no! It is so sad ),; okaay. Thanks a lot

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
