### ISSUE TITLE
Not all apps listed

### ISSUE THREAD

**Issue by MertCYLN** [Muirey03/Zenith#22]
I can’t  see all of my apps on the lists. (Even the ones I haven’t added to back of another app)

Can you let us see added apps w the check symbol on them on the list instead of not showing them after we add them

Sorry if I shouldn’t write some requests. I couldn’t add them to the request tab.

**Comment by Muirey03** [comment]
Duplicate issue. I am working on it.

**Comment by MertCYLN** [comment]
Thanks a lot

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
