### ISSUE TITLE
Crashes on app moving

### ISSUE THREAD

**Issue by MertCYLN** [Muirey03/Zenith#25]
When I long press on some app on the spring board to move it, all of the apps shakes forever and no gesture works. Hard boot requires.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Muirey03** [comment]
1) A hard boot will not be required, a respring via SSH will work just fine.
2) This sounds like a conflict with another tweak, does this still happen when ALL other tweaks are disabled in iCleaner?

**Comment by MertCYLN** [comment]
1. I am outside. So no computer.
2. It might be. It is hard to tell! Because it doesn’t do it all the time. It happens so rare. I have never experienced it before. I downloaded another tweak with yours. I thought the other one causes that, i deleted it. And it still continues. It happened the most when i try to move the apps which doesn’t appear on your tweak’s list!

I will try with disabling the other tweaks. I will let you know

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Muirey03** [comment]
If you can trigger it again, make sure you have CrashReporter installed so that you can send me a crash report.

**Comment by MertCYLN** [comment]
Deal 👍🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
