### ISSUE TITLE
Not an issue: the animations

### ISSUE THREAD

**Issue by MertCYLN** [Muirey03/Zenith#26]
While closing a zenith the animation is a little odd.

It doesn’t get smaller, it just slides back and I can see the little icon over the sliding ones. So it is not so well

Btw, is it possible to make animations synchronized w swiping? It opens after swiping through some far. Can’t the icons on the back track our fingers? Just like in the apex?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Muirey03** [comment]
Not an issue, won't be addressed, sorry.
