### ISSUE TITLE
Webclip crash

### ISSUE THREAD

**Issue by jffortier249** [Muirey03/Zenith#27]
I have a webclip created from a profile. If you try to add an app to it, it crash into safe mode. Crash reporter did not identify Zenith, I can send the crash report if you want.

**Comment by Muirey03** [comment]
Please send a crash report. What web clip where you using?

**Comment by jffortier249** [comment]
Crash report was send to your email. 

The webclip was one created with Apple Configurator and it's used for FileMaker and use the protocol fmp:// to launch a specified database

**Comment by Muirey03** [comment]
Unfortunately it seems as though these will not ever be able to be made compatible as they do not have a unique bundle id each and this is what Zenith uses to store your stacks. I will however fix this crash by making it so that they cannot be expanded in the first place.

**Comment by jffortier249** [comment]
Thanks, you use a different way to attach app then Apex, because it was possible before! But not a big deal!
