### ISSUE TITLE
Lag when there is a lot of them

### ISSUE THREAD

**Issue by CybrNight** [Muirey03/Zenith#29]
I have noticed that when there are a lot of nested apps on one page there is lag when scrolling between. I don’t remember having this issue with the original Apex so I’m hoping that this is just going to be fixed as the tweak is further developed.

**Comment by Muirey03** [comment]
I believe I have fixed this as much as I can in v.1.0.2

**Comment by ilyan30f** [comment]
still very laggy on iPhone X iOS 11.3.1

**Comment by ilyan30f** [comment]
When the visual indicator is set to “None”, lags dissappear.

**Comment by Muirey03** [comment]
@ilyan30f I know that, I know what's causing it but fixing it is a bit trickier. I think I have improved it though, please give me your email and I'll send you a test deb so you can tell me if it's better for you.

**Comment by ilyan30f** [comment]
Sure! I’d be glad to help on my favourite tweak and with and awesome dev! ilyan30f@gmail.com

**Comment by Muirey03** [comment]
@psychic2ombie @ilyan30f Please install v.1.0.3 which is now live on Chariz and tell me if it's fixed now

**Comment by CybrNight** [comment]
It is still very laggy on the newest version @Muirey03

**Comment by diamkil** [comment]
Still very laggy on latest version @Muirey03
