### ISSUE TITLE
Dock stacks do not space out properly. 

### ISSUE THREAD

**Issue by YouBetterChill** [Muirey03/Zenith#32]
iPhone X 11.3.1 all tweaks disabled except zenith via iCleaner and issue still persist.

**Comment by YouBetterChill** [comment]
![f47948b6-d4c4-4b6d-be79-977f05e93603](https://user-images.githubusercontent.com/35017579/49346016-55192180-f65a-11e8-9e98-d037176d93e4.png)

**Comment by Muirey03** [comment]
I believe this is fixed in v.1.0.1 - if not (when it is released), message me on twitter or Reddit please
