### ISSUE TITLE
API for integration with other tweaks

### ISSUE THREAD

**Issue by DavidGoldman** [Muirey03/Zenith#34]
Roughly the following API should be available:

```
+ (nullable NSArray<SBIcon *> *)zenithFolderIconsForIcon:(nonnull SBIcon *)icon;
```

Note that the API simply allows developers to recognize icons as Zenith folders and list the icons inside. For instance, ColorBadges could use this API to treat Zenith folders as normal folders.

**Comment by Muirey03** [comment]
Perfect. I will get the method done today and it will be available in v.1.0.2 when that is released

**Comment by Muirey03** [comment]
This has been added and will be available in v.1.0.2. The interface is:
```objective-c
@interface ZenithIconController : NSObject
+(nullable NSArray<SBApplicationIcon *> *)zenithFolderIconsForIcon:(nonnull SBApplicationIcon *)icon;
@end
```
so you can use it like this:
```objective-c
NSArray<SBApplicationIcon *> *zenithSubicons = [%c(ZenithIconController) zenithFolderIconsForIcon:self.icon];
```
@DavidGoldman
