### ISSUE TITLE
Can't close spotlight access?

### ISSUE THREAD

**Issue by cuticc** [Muirey03/Zenith#44]
1.Can't close spotlight access?
2.iphone X :There was a flicker when swiping up APP

**Comment by Muirey03** [comment]
That sounds like a conflict. Please tell me if it happens when all other tweaks are disabled using iCleaner Pro

**Comment by Muirey03** [comment]
@cuticc ^

**Comment by Muirey03** [comment]
I am closing this issue until you provide me with more information
