### ISSUE TITLE
Bug with FloatingDock

### ISSUE THREAD

**Issue by ilyan30f** [Muirey03/Zenith#45]
The grabbers extend too much when applied to apps in the dock. Also, it squares the dock.
![img_6860](https://user-images.githubusercontent.com/10600018/49973796-40b80d00-ff15-11e8-973a-0b200b594214.PNG)

**Comment by Muirey03** [comment]
The squared dock is a problem with Noctis and I believe the grabbers are a conflict with another tweak, please try and disable all other tweaks (leaving just Zenith and FloatingDock and tell me if this issue still occurs)

**Comment by ilyan30f** [comment]
The square issue is from Noctis. I’ll test the issue with the grabbers as they restore on respring, but stay as that after opening the group of icons of that app. The only tweaks I have on Dock are FiveIconDockXI and FloatingDock.

**Comment by Muirey03** [comment]
Fixed in v.1.1.1 - available soon
