### ISSUE TITLE
Aggregate badges not working 

### ISSUE THREAD

**Issue by jclegg555** [Muirey03/Zenith#46]
The badges on my stacks do not aggregate. I have numerous stacks that do not show badges at all until I swipe on them

**Comment by Muirey03** [comment]
This is probably a conflict with another tweak, does it still happen when all other tweaks are disabled using iCleaner? @jclegg555

**Comment by jclegg555** [comment]
I semirestored and installed unc0ver after the substrate release and everything  has functioning for me fine now. For some reason I still had one stack that did not aggregate badges. I figured out it was caused by the ‘ETA’ app from the App Store being on the top of the stack, possibly the app doesn’t show badges or something-I do have show badges set to on for it in settings though.

Regards,
Jeremy

**Comment by Muirey03** [comment]
Then it's plausible that the top app on a stack must have badges enabled for the aggregate badges feature to work - I'm closing this issue now
