### ISSUE TITLE
Updating apps removed them from the stack

### ISSUE THREAD

**Issue by NamitSingh14** [Muirey03/Zenith#47]
Everytime an app gets updated they are removed from the stack and placed at the end of the page

**Comment by Muirey03** [comment]
Are you running the latest version, this was fixed in v.1.0.3? A duplicate of the app could possibly still appear outside of the stack but the app should remain in the stack and the duplicate will disappear after a respring. @Fr0stP1xel

**Comment by Fr0stP1xel** [comment]
Yeah I checked it on the previous version. This was fixed in 1.0.3. Sorry for the issue! @Muirey03

**Comment by NamitSingh14** [comment]
Yeah I checked it on the previous version. This was fixed in 1.0.3. Sorry for the issue! @Muirey03
