### ISSUE TITLE
Random Crashes to Safemode

### ISSUE THREAD

**Issue by CybrNight** [Muirey03/Zenith#49]
So randomly I will crash and go into safemode. CrashReporter states SubstrateLoader and Zenith as suspects.

iPhone 7 Plus, iOS 11.1.2, Cydia Substrate 0.9.7 

Crash log:https://pastebin.com/2BAepTqq
Tweak list:https://pastebin.com/3Bqkfs9P

I’m thinking it’s an incompatibility with the new Substrate update.

**Comment by Muirey03** [comment]
Fixed in v.1.0.4
