### ISSUE TITLE
Tap and hold icon in Zenith stack?

### ISSUE THREAD

**Issue by swaggyP36000** [Muirey03/Zenith#5]
There should be a way to tap and hold an app in zenith, for example to remove it, without having to remove it from zenith first. Also, you might consider making it compatible with apps' 3D-touch menus.

**Comment by Muirey03** [comment]
Unfortunately this is impossible due to the fundamental way hit rendering works in UIKit. I'm sorry. If you want to uninstall an app that is part of a stack, you will have to first remove it from that stack.
