### ISSUE TITLE
Can't close folder from the bottom half of the screen

### ISSUE THREAD

**Issue by kraxarn** [Muirey03/Zenith#51]
When opening a folder and pressing the bottom half of the screen, nothing happens (it should close it). This is possibly related to using Bolders.

**Comment by Muirey03** [comment]
This is a conflict with Bolders, you should have got a popup alert view at some point telling you about this conflict.

**Comment by kraxarn** [comment]
It’s still an issue and a bug that has to be fixed with Zenith.
