### ISSUE TITLE
Maximum of 2 icons per row or column

### ISSUE THREAD

**Issue by kraxarn** [Muirey03/Zenith#52]
From the dock, it's only possible to create a maximum of 2 icons in each column. 
Apex 2 supported a maximum of 4 icons per column.

**Comment by Muirey03** [comment]
This is not an issue. Zenith works differently in the dock to Apex, Apex used to expand all 4 slots upwards whereas Zenith will expand two sideways and two upwards. This will not be changed,

**Comment by kraxarn** [comment]
It’s not an issue, it’s a feature request. If it’s supposed to expand sideways, it’s a bug as it doesn’t do that for me on iPhone X 11.3.1.
