### ISSUE TITLE
lost icon

### ISSUE THREAD

**Issue by tclfbedk** [Muirey03/Zenith#54]
I updated Electra from 1.0.3 to 1.1.0. I was stacking cydia and sileo on Electra's icon when using 1.0.3. Since I replaced Electra without releasing the stack, cydia etc on my homescreen disappeared. I uninstalled Zenith once, moved the stacked icons to a different folder, reinstalled, but cydia etc has disappeared from the folder and homescreen.
In the spotlight search, disappeared apps are displayed and can also be launched. I can not solve the problem because can't run Zenith without Electra. Help me.

**Comment by Muirey03** [comment]
I will add a "refresh settings" option to the preferences for you to reset your icon layout then. Thank you for reporting this.

**Comment by Muirey03** [comment]
Added a "reset all settings" button in v.1.0.5, that should fix your issue.
