### ISSUE TITLE
Moving icons causes safe mode

### ISSUE THREAD

**Issue by newuser1234565** [Muirey03/Zenith#56]
When in edit mode on the home screen, some icons duplicate themselves and then the phone takes no input and hangs until a respring/restart. Doesn't happen on every icon, but it appears to be icons not in a stack. Never tried moving a stack to replicate this bug. Really hoping for a fix as this always causes my home screen layout to revert to the state it was in pre-Zenith install.

**Comment by Muirey03** [comment]
This is probably a conflict, but I can't help you in any way without a crash report. Please send me one here using pastebin or something similar.

**Comment by newuser1234565** [comment]
Alright, how do I do that, with crashreporter?

**Comment by Muirey03** [comment]
Yes, CrashReporter

**Comment by newuser1234565** [comment]
Here is my most recent crash log: https://pastebin.com/TU9K0a87

Let me know if I did it wrong. Thanks.

**Comment by newuser1234565** [comment]
Posting new pastebin link as the previous one is set to expire in 1 day.

https://pastebin.com/NDsxHg4H

**Comment by Muirey03** [comment]
Could you install Cr4shed please and give me the report from that instead?

**Comment by Muirey03** [comment]
Closing this issue as you haven't responded
