### ISSUE TITLE
Deleted apps still in stack

### ISSUE THREAD

**Issue by mkwiimaster7** [Muirey03/Zenith#57]
Lets say you delete an app from settings while you have it in a stack. When you delete it and open the stack, the icon would be blank, and when you try to replace it, you get sent to safe mode

**Comment by Muirey03** [comment]
Just to confirm, this only happens with stock/cydia apps right, not apps from the app store?

**Comment by mkwiimaster7** [comment]
Yes just stock/cydia apps

**Comment by Muirey03** [comment]
Duplicate issue: https://github.com/Muirey03/Zenith/issues/41
