### ISSUE TITLE
Download on Sileo not working (Error: Expected size 232602, got 217822 instead)

### ISSUE THREAD

**Issue by martinmacfly** [Muirey03/Zenith#58]
Hi, i bought the Tweak today but the download is not working. 
Is this a known issue?

"Error: Expected size 232602, got 217822 instead"

How do i get this to work?

**Comment by Muirey03** [comment]
This is not my fault, but Sileo/Chariz's fault. Please install via Cydia instead.

**Comment by martinmacfly** [comment]
Thanks for the reply, already tried that. But after installation it wont show up in the settings.

**Comment by Muirey03** [comment]
So ignore Sileo (no idea if this will be fixed, I'll contact kirb). Reinstall it from Cydia and respring. If it still doesn't appear to be installed, go to cydia and look at the "Installed" list to see if it installed correctly. If not, send me any error messages cydia gave

**Comment by martinmacfly** [comment]
weird, i installed it via cydia. and it went through without an error. Still its not showing in my settings.
Even rejailbreaked. (im on ios 11.3.1 and jailbreaked with the latest electra release)

**Comment by Muirey03** [comment]
Okay a few things:
1. Does it show up in the "installed" list in cydia?
2. What files does it show in the filesystem content section in its cydia page?
3. What jailbreak, iOS version and device are you using?
4. Does the file /Library/MobileSubstrate/DynamicLibraries/Zenith.dylib exist?
5. Does the icon expand to show the pluses when you swipe down/up on it?

**Comment by martinmacfly** [comment]
1. Yes
2. 
![img_6492](https://user-images.githubusercontent.com/47869408/53286988-3f595b00-3776-11e9-8d3e-3794794308e9.jpg)
3. iPhone 6s, iOS 11.3.1 jailbreaked with latest electra release
4. Yes
5. No

**Comment by Muirey03** [comment]
That's really odd, what do you see in /Library/MobileSubstrate/DynamicLibraries/Zenith.plist?

**Comment by martinmacfly** [comment]
Hi,
i did a full restore and rejailbreaked. now its working!

Thanks for your support!

**Comment by Muirey03** [comment]
Glad to hear it, enjoy the tweak!
