### ISSUE TITLE
Weird behaviour with FloatingDock

### ISSUE THREAD

**Issue by BitGrub** [Muirey03/Zenith#59]
Zenith'd apps in the dock spread downwards (below screen). Also the app that spreads upwards is far far away

**Comment by Muirey03** [comment]
Duplicate issue: https://github.com/Muirey03/Zenith/issues/45

**Comment by BitGrub** [comment]
It’s actually two different issues caused by the same tweak conflict but ok.

Also you’re a legend for porting Apex, I love you so much
