### ISSUE TITLE
Deleted apps have gray entry

### ISSUE THREAD

**Issue by TheWarDoctor88** [Muirey03/Zenith#60]
When I upgraded to iOS 12.1.2, some user preferences carried over. Doing so kept my app set up with zenith and apps I didn’t re-install, left a grey entry in the spot it was set with zenith. When trying to delete or place a new app in the slot, I get sent to safe mode. I’ve deleted zenith, and went into Filza to delete left over files and deleted all the files I could there. The issue still persists even after fresh install of zenith. The only way to “fix” the issue is to re-install the app the was there (found out which app it was with the entry of a plist file).

**Comment by Muirey03** [comment]
Fixed in v.1.0.7 which should be available very soon.
