### ISSUE TITLE
Opening multiple apps

### ISSUE THREAD

**Issue by cbendrey** [Muirey03/Zenith#61]
I'm using zenith on the dock. I have 3 icons in a stack. When I tap the middle icon, both the top middle app and the top app open (in that order so I'm left in the top app rather than the one I tried to open!)

I'm using FloatingDock as well.

**Comment by Muirey03** [comment]
Does this issue still happen when all other tweaks are disabled?

**Comment by cbendrey** [comment]
When i re-enable betterfivecolumnhomescreen with floatingdock the problem occurs. Either on their own works fine

**Comment by tiego97** [comment]
I am having this issue also, but it’s not limited to the dock.

**Comment by cbendrey** [comment]
The latest version seems to have fixed it for me

**Comment by Muirey03** [comment]
Fixed in 1.0.7
