### ISSUE TITLE
Removing packages with SB icons after Cydia uninstall

### ISSUE THREAD

**Issue by manabites** [Muirey03/Zenith#69]
Replication:
-Install tweak through Cydia that has a SpringBoard icon (Flex, BytaFont3, etc.).
-Place icon inside stack.
-Remove tweak through Cydia.
-Attempt to remove blank space from stack
   -Phone should now enter Safe Mode

**Comment by Muirey03** [comment]
This was fixed in v.1.0.7 which should be available this weekend
