### ISSUE TITLE
Facebook as a permanent -1 badge

### ISSUE THREAD

**Issue by fido7up** [Muirey03/Zenith#7]
Facebook as a permanent -1 badge, I saw other people saying the same on reddit.  

Tried :  
- Reinstalling the tweak, the app. 
- Respring 
- Rejailbreak (Electra)  

My facebook app doesn't have any tweaks or modification.

It goes away when expending but comes back when shrinking, and changes when the app as a real notification.

**Comment by Muirey03** [comment]
When you get a real notification for facebook, does the badge go back to 1 or does it go to 0 or stay at -1 or something?

**Comment by fido7up** [comment]
When I get a real one, it goes to 1 and when I check it it turns back to -1.

**Comment by Muirey03** [comment]
Thank you, I think it should be easy enough to fix. What's your email so I can send you a test deb when I'm ready?

**Comment by Muirey03** [comment]
I believe I've fixed this, once you send me your email, I'll send you the deb for you to test. @fido7up

**Comment by Reygok** [comment]
You can send it to me, too, cuz I have the same bug :) But not only with the FB app, also with TvShowTime.

**Comment by Muirey03** [comment]
@Reygok I can't send it to anyone if you don't give me your email...

**Comment by Reygok** [comment]
I know, I was searching for a way to send you a message here but github doesnt seem to have that functionality... well here you go:
reygok3@outlook.com

**Comment by Muirey03** [comment]
@Reygok I emailed it to you, hopefully that fixed it

**Comment by Reygok** [comment]
I think it did, I had a friend send me a test notification, it went to 1, I checked it, and it went away. No -1 anymore :D

**Comment by Reygok** [comment]
There seems to ba another bug though, but that may be an incompatibility with FullFolders. I cannot close fullscreen folders anymore like I used to, by tapping the background. If I disable either cephei or fullfolders, it works fine

**Comment by Muirey03** [comment]
Yes, this is an issue with FullFolders, sorry.

**Comment by Muirey03** [comment]
Closing this issue as the badge number bug is fixed in v.1.0.1
