### ISSUE TITLE
Immediate safe mode after updating to 1.0.7

### ISSUE THREAD

**Issue by mllrr96** [Muirey03/Zenith#70]
Hello, so I just updated Zenith to v. 1.0.7 and my phone went to safe mode, reports from Cr4shed and CrashReportor and tweak list  down below 

Cr4shed report 
https://pastebin.com/b9Gj5hfW

CrashReport
https://pastebin.com/J1C94zCT

TweakList
https://pastebin.com/w1A1fv1s

**Comment by Muirey03** [comment]
Fixed in 1.0.7-2
