### ISSUE TITLE
Wrong app opens

### ISSUE THREAD

**Issue by ghost** [Muirey03/Zenith#71]
After opening your stack and selecting one of the apps within the stack, the one that opens is the app that’s on the home screen.

**Comment by callmeishman** [comment]
Same issue, occurred after 1.0.7 update. 
When tapping app in stack, the primary app on the home screen will launch in the foreground and the stack app will launch in the background simultaneously. Once this occurs, issue doesn’t happen again with the same stack until after a respring.

**Comment by Muirey03** [comment]
Fixed in 1.0.8-1

**Comment by hollywoodDeadz** [comment]
Still happens for me after upgrading to 1.0.8-1
