### ISSUE TITLE
Cannot edit stacks on iPad 

### ISSUE THREAD

**Issue by i0ntempest** [Muirey03/Zenith#72]
As the title says, holding the center icon after expanding a stack will only move the icon on the springboard.

**Comment by Muirey03** [comment]
What about holding one of the sub-apps?

**Comment by i0ntempest** [comment]
Nope, still just moves the icon. Btw I'm on iOS 11.2.5.

**Comment by Muirey03** [comment]
Is this still occuring with the latest version of Zenith?

**Comment by i0ntempest** [comment]
Yes, just confirmed it's still occurring.

**Comment by Muirey03** [comment]
Does it work on any previous versions such as v.1.0.5 or 1.0.6?

**Comment by i0ntempest** [comment]
Sorry for the late response, I think I started trying it since it's released on Cydia and it had the problem since then.

**Comment by Muirey03** [comment]
I don't have an iPad so I can't fix this, sorry
