### ISSUE TITLE
Apps trampling when using a RTL language

### ISSUE THREAD

**Issue by harel013** [Muirey03/Zenith#73]
First of all thank you very much for your awesome work, I just have 2 little problems with stacking and apps that tramples each other when I make the gesture to open them.
I upload screen recording to Dropbox that describe best what I have.
I’m on ipx latest ver of Zenith and without one tweak that can interfere with that.
Thank you very much for your help. 🙏🏼 

https://www.dropbox.com/sh/a7z1g0axzk37utr/AABJMX6_2tRr2thkNXRKRxx_a?dl=0

**Comment by Muirey03** [comment]
Does this still happen when all other tweaks are disabled?

**Comment by harel013** [comment]
Found the issue: RTL language not supported sorry for the misunderstanding

**Comment by Muirey03** [comment]
Fixed now
