### ISSUE TITLE
Conflict with Primalfolder and Snowboard (I think)

### ISSUE THREAD

**Issue by moegana** [Muirey03/Zenith#77]
ios 12.1.1 unc0ver b3v46
I have no idea what's causing this snowboard issue, as it happens even without any themes active. It might not even have anything to do with snowboard, but it seemed to go away when everything was disabled and snowboard was the only tweak enabled. It might have something to do with the visual bug where grabbers don't disable until you trigger the zenith animation or the one with icons sometimes overlapping. I recorded it below.
https://files.catbox.moe/3ycp9j.MP4

The primalfolder bug slows my phone down to a halt and opens the wrong apps, so I'd rather not attempt to duplicate it (I had a hard time getting to cydia in order to uninstall zenith due to the wrong app opening and didn't have icleaner installed at the time). My guess is that it has to do with the "Tap to close" option in primalfolder, as I'm currently running primalfolder without issue with that option disabled. It happened with that option enabled in conjunction with zenith apps in a folder. I think it might've been from the tap gesture closing both zenith's add menu and the folder that contained the icons that were being zenith's.

**Comment by Muirey03** [comment]
It is an issue with SnowBoard, add Spark's repo and update to the latest version to fix it.
