### ISSUE TITLE
Updating apps

### ISSUE THREAD

**Issue by hollywoodDeadz** [Muirey03/Zenith#79]
When apps update they come out of the folders

**Comment by Muirey03** [comment]
Does a respring add them back to the folder?

**Comment by hollywoodDeadz** [comment]
Yea it does, I thought it was a glitch so I reinstalled the tweak and it still happens on occasion

**Comment by Muirey03** [comment]
If a respring fixes it, then I don't see this as an important issue and am closing it, sorry.
