### ISSUE TITLE
Youtube is not selectable

### ISSUE THREAD

**Issue by fido7up** [Muirey03/Zenith#8]
The youtube app does not show in the selectable app, but the tweak can be used on it.

Other apps that are not installed by the App Store behave like that also.

Tried :
- Reinstalling the tweak, the app.
- Respring
- Rejailbreak (Electra)

**Comment by Muirey03** [comment]
Other people have reported this issue with the Camera, Safari and App Store apps, I'll look into it, thank you for reporting it.

**Comment by Muirey03** [comment]
Fixed in v.1.0.1
