### ISSUE TITLE
[Request] Compatibility with spotCC 

### ISSUE THREAD

**Issue by wow17** [Muirey03/Zenith#80]
spotCC is a tweak allowing you to swipe down anywhere on the springboard as you would to bring up spotlight search but instead it brings down the control center. That way you don’t have to reach all the way in the corner on larger devices. It is a great convince/time saver and I would appreciate it if these two could work together.

**Comment by Muirey03** [comment]
I don’t understand how they could ever work together as the gestures would conflict. Sorry but compatability will never be added.

**Comment by wow17** [comment]
How would they conflict? You currently allow the same pull down gesture to pull down the spotlight search while allowing a swipe up to activate the hidden apps. Why not just change it to pull down control center instead of spotlight and you could still activate spotlight via the status bar tap.
