### ISSUE TITLE
Lags on Xs max 

### ISSUE THREAD

**Issue by KuroAMK** [Muirey03/Zenith#82]
Hi, 

It seems that it lags on XS Max. Could you maybe look into that ?

**Comment by systox** [comment]
Hmm, what do you mean by lag? I'm also on XS Max and I'm not seeing any stutter or increased load times

**Comment by KuroAMK** [comment]
When I have App selector open (the one with the x on the left to uninstall) it seems to stutter. 

https://streamable.com/9ysks

Also: If you create a Stack and remove the app you created the stack with, the other apps in the stack gets hidden until you reset home layout

**Comment by systox** [comment]
Hey kuro, great video of the issue. I set my home screens like yours and tried to replicate the stuttering on my XS max but couldn’t. Do you by any chance use xenhtml? I don’t have it and I hear it may be causing lag for some people when used with this tweak.

**Comment by Muirey03** [comment]
Duplicate issue: #65, I am working on fixing it
