### ISSUE TITLE
Safe mode when openning an app with bioprotect

### ISSUE THREAD

**Issue by ghost** [Muirey03/Zenith#83]
First thanks for your tweak, apex was with dark theme the main reason for me to jailbreak, I’m really happy to see that your tweak does it for iOS 12.

For the bug, I created a stack in my dock with some apps (stack on dialer, whatsapp discord facetime and skype in the stack)
Facetime is locked with bioprotect, when I open it from the stack, it ask me to unlock, an crash (safe mode) after that.

Could you take a look on that please ?
Thanks,
Julien

**Comment by Muirey03** [comment]
There's nothing I can do about this I'm afraid. I've tried contacting limneos about it but he won't respond so I can't really ever get this fixed.
