### ISSUE TITLE
[Conflict] Zenith Disables EZswipe (Packix repo)

### ISSUE THREAD

**Issue by systox** [Muirey03/Zenith#84]
iPhone XS Max 12.0.1

EZswipe allows triggering 3 different screen depending on where you swipe down on home screen (left edge - middle - right edge). I like this on XS Max because I don't have to reach for top of screen and can easily access control center, spotlight, and notifications.

I noticed zenith has a switch for swipe down action on home screen. Is it possible to either restore compatibility with EZswipe by P2KDev or implement similar functionality in zenith swipe down homescreen action?

**Comment by raypee** [comment]
I've the same problem on my iPhone 8 Plus 12.1.2 😔

**Comment by Muirey03** [comment]
This can't be fixed as the gestures conflict, sorry.
