### ISSUE TITLE
Badge appearing when expending or shrinking

### ISSUE THREAD

**Issue by fido7up** [Muirey03/Zenith#9]
Some times a badge 1 appears for just enough time for me to read the 1 and goes away when  expending or shrinking an icon.

It only happened, for now, with the WhatsApp app in the right space of the doc.
Happens with normal use, can't manage to do it on purpose.

Important note : I have OnlineNotify which could be interfering with it. Will update if it appears somewhere else or without the tweak.

Edit : Happens without OnlineNotify also.
Edit 2 : After a respring it happened without me touching the icon, 1 appeared twice.

**Comment by Muirey03** [comment]
Does this issue still occur when all other tweaks are disabled? See if you can work out what the culprit is and I'll do my best to fix it.
