### ISSUE TITLE
Notification badges from apps under stack not showing..

### ISSUE THREAD

**Issue by paulmoons** [Muirey03/Zenith#90]
I have a simple Zenith stack with Facebook on top and Facebook Messenger underneath. Both apps have badges activated but badges from Messenger never make it onto the top of the stack. 

I have tried disabling (and changing settings) with any tweaks that affect icons but no dice. These tweaks include ColourBadges (with Zenith support on and off) Iconizer (off) and AppCon (off).

Are there any known conflicts to avoid and is there a fix?

Cheers.

**Comment by Muirey03** [comment]
Does the issue still happen after disabling all other tweaks using iCleaner pro? Do you definitely have the "Aggregate badges" option in Zenith's settings enabled?

**Comment by paulmoons** [comment]
Thanks for looking into this. Unfortunately I do not have iCleaner Pro just regular iCleaner. I definitely have aggregate badges on in Zenith and I turned the tweaks off via their own settings - both AppCon and Iconizer have settings to disable themselves.

**Comment by Muirey03** [comment]
Please download iCleaner pro and try disabling all other tweaks.

**Comment by paulmoons** [comment]
Hello and thanks again. I downloaded iCleaner Pro and tried a few things but no dice. First I disabled all tweaks that I could resonably consider icon related one by one. These were:

Anemone
Appcon
ColorBadges
Iconizer
Iconoclasm
OpenNotofier11 - Tateu
SpringPlus11

No dice. I then tried to disable all of them at once but still no changed. 

Finally I disabled every tweak bar zenith and iCleaner Pro and even this did not bring the notification from inside he stack to the fore. Throughout this process I sent myself new messages to create new notifications but but nothing appeared on the top of the stack.

Interestingly, while testing I did receive a Facebook message (my stack is FB on top with Messenger underneath) and a badge appeared with 2 on it to signify 1 FB message and 1 Messenger message. 

However, once I cleared the FB message (leaving Messenger alone), the notification disappeared and the remaining Messenger notification could only be seen once I opened the stack as before.

:/

**Comment by paulmoons** [comment]
And so without any warning (or updates or re-springs or anything else obvious) the badge started working. 

??? 

Go figure.

**Comment by Muirey03** [comment]
All apps in the stack need their notification badges enabled in settings for it to work properly.

**Comment by paulmoons** [comment]
> All apps in the stack need their notification badges enabled in settings for it to work properly.

Yeah.. that's not it. Always had those settings enabled. Literally no change.
