### ISSUE TITLE
App Icon size not adjusting with portrait / landscape mode (iPad 6)

### ISSUE THREAD

**Issue by FatherFef** [Muirey03/Zenith#92]
Just installed on my iPad. I use my iPad mostly in landscape and the tweak works great. When i turn to portrait, the hidden apps expand larger than the home app icon. Or better said, the app scaling stays in landscape and does not change to portrait size.

**Comment by Muirey03** [comment]
Can you send a screenshot please?

**Comment by Muirey03** [comment]
I don't have an iPad to test this on, so I can't fix it, sorry.
