### ISSUE TITLE
Zenith and Springfinity don’t play nice together

### ISSUE THREAD

**Issue by inkrypted** [Muirey03/Zenith#93]
When using Springfinity zenith can not be activated. Can you please add the double tap icon function that originally was used for Apex2, that would solve the incompatibility between both tweaks

**Comment by Muirey03** [comment]
This cannot be fixed, sorry.

**Comment by inkrypted** [comment]
Soooo you don’t no how to make it do a double tap option is what your saying.  Nothing is broken to be fixed.

**Comment by Muirey03** [comment]
Adding a double-tap option will make opening apps **very** slow.

**Comment by inkrypted** [comment]
That’s understandable thank you for elaborating.
