### ISSUE TITLE
Icons in Dock don’t expand all the way

### ISSUE THREAD

**Issue by Sn0wStorm** [Muirey03/Zenith#94]
When expanding an icon in the Dock with the new 1.1.1 update, the icons behind only move out halfway and it becomes hard to click them.
Also the Labels are shown even though this is disabled in the settings.
Only FiveIconDock installed that modifies the Dock but i tried disabling every tweak in iCleaner and the issue still persists.
iPhone XS 12.0.1 newest Chimera and Sileo
![876751CC-0AEF-414F-86E6-22C2CA8AF562](https://user-images.githubusercontent.com/4077108/58201153-b00c0700-7cd4-11e9-949e-75d5aa63bf17.jpeg)

**Comment by deadman96385** [comment]
I have the same issue on my XS Max with FiveIconDock

**Comment by Sn0wStorm** [comment]
Fixed with the update
